name: CI

on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    secrets:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
